language: rust
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview --toolchain nightly 
  - rustup component add clippy-preview --toolchain nightly
script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo build --verbose --all
  - cargo test --verbose --all